spring.application.name=backend

# ==============================
# CONFIGURACI�N DE LA BASE DE DATOS
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/fixfast?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# ==============================
# JPA / HIBERNATE
# ==============================
# update --> crea las tablas si no existen y mantiene los datos
spring.jpa.hibernate.ddl-auto=update

# Para ver las consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ==============================
# SERVER (opcional)
# ==============================
server.port=8080
